version: '3'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3010:3010"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/users
      - PORT=3010
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - WDS_SOCKET_PORT=0

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local